# Generated by Django 5.0.4 on 2024-04-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_importants_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'ToDo', 'verbose_name_plural': 'ToDos'},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='memo',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='importants_level',
            new_name='rating',
        ),
    ]
